### ISSUE TITLE
作者 你好请问这个是否实现了自动 ，定时操作手机

### ISSUE THREAD

**Issue by ruixule** [itning/GetUpEarly#18]
1 蚂蚁森林
2 蚂蚁庄园 还有其他功能

**Comment by itning** [comment]
不是自动的
from 阿里邮箱 iPhone------------------------------------------------------------------
***@***.***>
日　期：2022年09月16日 23:35:31
***@***.***>
***@***.***>
主　题：[itning/GetUpEarly] 作者 你好请问这个是否实现了自动 ，定时操作手机 (Issue #18)

1 蚂蚁森林
 2 蚂蚁庄园 还有其他功能
