### ISSUE TITLE
感谢开发者辛苦码代码

### ISSUE THREAD

**Issue by jackberry** [itning/GetUpEarly#5]
请问是否可以增加微博打卡，oppo社区的早起打卡，和欢太商城的早睡打卡

**Comment by itning** [comment]
> 请问是否可以增加微博打卡，oppo社区的早起打卡，和欢太商城的早睡打卡

微博打卡指的什么，有截图吗，目前有微博早起打卡

**Comment by lwq12342** [comment]
怎么使用啊，小白，求大佬教学
