### ISSUE TITLE
求问如何运行

### ISSUE THREAD

**Issue by nanshark** [itning/GetUpEarly#6]
求问如何运行，看截图来说这个是有APP的嘛？咋没有下载地址呢？

**Comment by itning** [comment]
[Github下载页面](https://github.com/itning/GetUpEarly/releases)

**Comment by nanshark** [comment]
大佬牛B，我想问一下这个是自己手动点还是到时间自动执行，如果自动执行的话需要进行什么设置啊，谢谢大佬。

**Comment by itning** [comment]
手动的哈
