### ISSUE TITLE
how to use it？

### ISSUE THREAD

**Issue by ruixule** [itning/GetUpEarly#8]
Dear ，how to use it，Is there any documentation？

**Comment by ruixule** [comment]
是自动操作的吗

**Comment by itning** [comment]
This is Android app, you can download app from [github release page](https://github.com/itning/GetUpEarly/releases)

**Comment by itning** [comment]
> 是自动操作的吗

不是

**Comment by ruixule** [comment]
> This is Android app, you can download app from [github release page](https://github.com/itning/GetUpEarly/releases)

thanks 。so later
